about/urls.py
from django.urls import path

from . import views

app_name = "about"
urlpatterns = [
    path("", views.about, name="about"),
    path("privacy/", views.privacy, name="privacy"),
    path("terms/", views.terms, name="terms"),
]

blog/urls.py
from django.urls import path

from . import views

app_name = "blog"
urlpatterns = [
    path("", views.index, name="blog"),
]

events/urls.py
from django.urls import path

from . import views

app_name = "events"
urlpatterns = [
    path("", views.index, name="events"),
]

friends/urls.py
from django.urls import path

from . import views

app_name = "friends"
urlpatterns = [
    path("", views.index, name="friends"),
]

public_python/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("web.urls", namespace="web")),
    path("events/", include("events.urls", namespace="events")),
    path("friends/", include("friends.urls", namespace="friends")),
    path("blog/", include("blog.urls", namespace="blog")),
    path("about/", include("about.urls", namespace="about")),
    path("admin/", admin.site.urls),
]

web/urls.py
from django.urls import path

from . import views

app_name = "web"
urlpatterns = [
    path("", views.home, name="home"),
]

about/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models

# Create your models here.

events/models.py
from django.db import models

# Create your models here.


class Event(models.Model):
    header = models.CharField(max_length=64)
    content = models.CharField(max_length=1000)
    is_visible = models.BinaryField()
    is_removed = models.BinaryField()
    link = models.CharField(max_length=128)

friends/models.py
from django.db import models

# Create your models here.


class Friend(models.Model):
    header = models.CharField(max_length=64)
    content = models.CharField(max_length=256)
    link = models.CharField(max_length=128)

web/models.py
from django.db import models


class Slide(models.Model):
    header = models.CharField(max_length=64)
    content = models.CharField(max_length=256)
    image = models.CharField(max_length=128)


class Service(models.Model):
    header = models.CharField(max_length=64)
    content = models.CharField(max_length=256)
    image = models.CharField(max_length=128)


class Condition(models.Model):
    question = models.CharField(max_length=64)
    answer = models.CharField(max_length=512)

about/views.py
from django.shortcuts import render

# Create your views here.


def about(request):
    return render(request, "about/info.html")


def privacy(request):
    return render(request, "about/info.html")


def terms(request):
    return render(request, "about/info.html")

blog/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, "blog/blog.html")

events/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, "events/events.html")

friends/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, "friends/friends.html")

web/views.py
from django.shortcuts import render
from .models import Slide, Service, Condition


# Create your views here.


def home(request):
    slides = Slide.objects.all()
    services = Service.objects.all()
    conditions = Condition.objects.all()
    context = {
        "slide_list": slides,
        "service_list": services,
        "odd_condition_list": conditions[1::2],
        "even_condition_list": conditions[::2],
    }
    return render(request, "web/home.html", context)

templates/about/info.html
{% extends "base.html" %}

{% block content %}
<section class="container pt-5">
	<div class="row">
		<div class="col-12 text-center">
			<h1 class="text-body-emphasis">About it & FAQs</h1>
			<p class="col-lg-8 mx-auto lead">
				This takes the basic jumbotron above and makes its background
				edge-to-edge with a <code>.container</code> inside to align content.
				Similar to above, it's been recreated with built-in grid and utility
				classes.
			</p>
		</div>
		<div class="col-12 text-center">
			<img src="/assets/img/star.png" alt="star">
			<img src="/assets/img/star.png" alt="star">
			<img src="/assets/img/star.png" alt="star">
			<img src="/assets/img/star.png" alt="star">
			<img src="/assets/img/star.png" alt="star">
		</div>
	</div>
</section>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en" class="h-100">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>SinkrOne</title>
	{% load static %}
	<!-- ======= Favicon ======= -->
	<link rel="icon" type="image/x-icon" href="{% static 'img/star.png' %}" />
	<!-- ======= Stylesheets ======= -->
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
	<link href="{% static 'css/sinkrone.min.css' %}" rel="stylesheet">
</head>

<body class="d-flex flex-column h-100">
	<!-- ======= Icons ======= -->
	<svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
		<symbol id="bootstrap" viewBox="0 0 118 94">
			<title>Bootstrap</title>
			<path fill-rule="evenodd" clip-rule="evenodd"
				d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z">
			</path>
		</symbol>
		{% block icons %}{% endblock %}
	</svg>

	<!-- ======= Header ======= -->
	<header class="container-flued border-bottom fixed-top bg-body-tertiary">
		<nav class="navbar navbar-expand-md rounded">
			<div class="container">
				<a class="navbar-brand" href="{% url 'web:home' %}">SinkrOne</a>
				<button class="navbar-toggler my-2" type="button" data-bs-toggle="collapse" data-bs-target="#navbar1"
					aria-controls="navbar1" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse py-2" id="navbar1">
					<form class="input-group"><input type="search" class="form-control" placeholder="Search"
							aria-label="Search" aria-describedby="button1">
						<button class="btn btn-primary" type="submit" id="button1">Search</button>
					</form>
					<ul class="navbar-nav justify-content-md-center mx-2">
						<li class="nav-item mx-2"><a href="{% url 'events:events' %}" class="nav-link">Events</a></li>
						<li class="nav-item mx-2"><a href="{% url 'friends:friends' %}" class="nav-link">Friends</a>
						</li>
						<li class="nav-item mx-2"><a href="{% url 'blog:blog' %}" class="nav-link">News</a></li>
						<li class="nav-item mx-2"><a href="{% url 'about:about' %}" class="nav-link">About</a></li>
					</ul>
					<button type="button" class="btn btn-primary col-md" data-bs-toggle="modal"
						data-bs-target="#exampleModalScrollable">
						Create
					</button>
				</div>
			</div>
		</nav>
	</header>

	<!-- ======= Modal ======= -->
	<div class="modal fade" id="exampleModalScrollable" tabindex="-1" aria-labelledby="exampleModalScrollableTitle"
		aria-hidden="true" style="display: none;">
		<div class="modal-dialog modal-dialog-scrollable">
			<div class="modal-content">
				<div class="modal-header">
					<h1 class="modal-title fs-5" id="exampleModalScrollableTitle">
						Modal title
					</h1>
					<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
				</div>
				<div class="modal-body">
					<p>
						This is some placeholder content to show the scrolling
						behavior for modals. We use repeated line breaks to
						demonstrate how content can exceed minimum inner height,
						thereby showing inner scrolling. When content becomes longer
						than the predefined max-height of modal, content will be
						cropped and scrollable within the modal.
					</p>
					<p>
						This content should appear at the bottom after you scroll.
					</p>
				</div>
				<div class="modal-footer">
					<button type="button" class="btn btn-secondary" data-bs-dismiss="modal">
						Cancel
					</button>
					<button type="button" class="btn btn-primary">
						Save
					</button>
				</div>
			</div>
		</div>
	</div>

	<!-- ======= Content ======= -->
	{% block content %}{% endblock %}

	<!-- ======= Footer ======= -->
	<footer class="container pt-5  mt-auto">
		<div class="d-flex flex-wrap justify-content-between align-items-center py-3 border-top">
			<p class="col-md-4 mb-0 text-body-secondary">© 2023 SinkrOne</p>
			<a href="#"
				class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
				<svg class="bi me-2" width="40" height="32">
					<use xlink:href="#bootstrap"></use>
				</svg>
			</a>
			<ul class="nav col-md-4 justify-content-end">
				<li class="nav-item">
					<a href="{% url 'about:privacy' %}" class="nav-link px-2 text-body-secondary">Privacy</a>
				</li>
				<li class="nav-item">
					<a href="{% url 'about:terms' %}" class="nav-link px-2 text-body-secondary">Terms</a>
				</li>
			</ul>
		</div>
	</footer>

	<!-- ======= Javascript ======= -->
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
</body>

</html>

templates/blog/blog.html
{% extends "base.html" %}

{% block content %}
<section class="container">
	<div class="row g-5 py-5">
		<div class="col-md-8">
			<article class="blog-post">
				<h2 class="blog-post-title mb-1">Sample blog post</h2>
				<p class="blog-post-meta">January 1, 2021 by <a href="#">Mark</a></p>

				<p>This blog post shows a few different types of content that’s supported and styled with Bootstrap.
					Basic typography, lists, tables, images, code, and more are all supported as expected.</p>
				<hr>
				<p>This is some additional paragraph placeholder content. It has been written to fill the available
					space and show how a longer snippet of text affects the surrounding content. We'll repeat it
					often
					to keep the demonstration flowing, so be on the lookout for this exact same string of text.</p>
				<h2>Blockquotes</h2>
				<p>This is an example blockquote in action:</p>
				<blockquote class="blockquote">
					<p>Quoted text goes here.</p>
				</blockquote>
				<p>This is some additional paragraph placeholder content. It has been written to fill the available
					space and show how a longer snippet of text affects the surrounding content. We'll repeat it
					often
					to keep the demonstration flowing, so be on the lookout for this exact same string of text.</p>
				<h3>Example lists</h3>
				<p>This is some additional paragraph placeholder content. It's a slightly shorter version of the
					other
					highly repetitive body text used throughout. This is an example unordered list:</p>
				<ul>
					<li>First list item</li>
					<li>Second list item with a longer description</li>
					<li>Third list item to close it out</li>
				</ul>
				<p>And this is an ordered list:</p>
				<ol>
					<li>First list item</li>
					<li>Second list item with a longer description</li>
					<li>Third list item to close it out</li>
				</ol>
				<p>And this is a definition list:</p>
				<dl>
					<dt>HyperText Markup Language (HTML)</dt>
					<dd>The language used to describe and define the content of a Web page</dd>
					<dt>Cascading Style Sheets (CSS)</dt>
					<dd>Used to describe the appearance of Web content</dd>
					<dt>JavaScript (JS)</dt>
					<dd>The programming language used to build advanced Web sites and applications</dd>
				</dl>
				<h2>Inline HTML elements</h2>
				<p>HTML defines a long list of available inline tags, a complete list of which can be found on the
					<a href="https://developer.mozilla.org/en-US/docs/Web/HTML/Element">Mozilla Developer
						Network</a>.
				</p>
				<ul>
					<li><strong>To bold text</strong>, use <code
							class="language-plaintext highlighter-rouge">&lt;strong&gt;</code>.</li>
					<li><em>To italicize text</em>, use <code
							class="language-plaintext highlighter-rouge">&lt;em&gt;</code>.</li>
					<li>Abbreviations, like <abbr title="HyperText Markup Language">HTML</abbr> should use <code
							class="language-plaintext highlighter-rouge">&lt;abbr&gt;</code>, with an optional <code
							class="language-plaintext highlighter-rouge">title</code> attribute for the full phrase.
					</li>
					<li>Citations, like <cite>— Mark Otto</cite>, should use <code
							class="language-plaintext highlighter-rouge">&lt;cite&gt;</code>.</li>
					<li><del>Deleted</del> text should use <code
							class="language-plaintext highlighter-rouge">&lt;del&gt;</code> and <ins>inserted</ins>
						text
						should use <code class="language-plaintext highlighter-rouge">&lt;ins&gt;</code>.</li>
					<li>Superscript <sup>text</sup> uses <code
							class="language-plaintext highlighter-rouge">&lt;sup&gt;</code> and subscript
						<sub>text</sub> uses <code class="language-plaintext highlighter-rouge">&lt;sub&gt;</code>.
					</li>
				</ul>
				<p>Most of these elements are styled by browsers with few modifications on our part.</p>
				<h2>Heading</h2>
				<p>This is some additional paragraph placeholder content. It has been written to fill the available
					space and show how a longer snippet of text affects the surrounding content. We'll repeat it
					often
					to keep the demonstration flowing, so be on the lookout for this exact same string of text.</p>
				<h3>Sub-heading</h3>
				<p>This is some additional paragraph placeholder content. It has been written to fill the available
					space and show how a longer snippet of text affects the surrounding content. We'll repeat it
					often
					to keep the demonstration flowing, so be on the lookout for this exact same string of text.</p>
				<pre><code>Example code block</code></pre>
				<p>This is some additional paragraph placeholder content. It's a slightly shorter version of the
					other
					highly repetitive body text used throughout.</p>
			</article>

			<article class="blog-post">
				<h2 class="blog-post-title mb-1">Another blog post</h2>
				<p class="blog-post-meta">December 23, 2020 by <a href="#">Jacob</a></p>

				<p>This is some additional paragraph placeholder content. It has been written to fill the available
					space and show how a longer snippet of text affects the surrounding content. We'll repeat it
					often
					to keep the demonstration flowing, so be on the lookout for this exact same string of text.</p>
				<blockquote>
					<p>Longer quote goes here, maybe with some <strong>emphasized text</strong> in the middle of it.
					</p>
				</blockquote>
				<p>This is some additional paragraph placeholder content. It has been written to fill the available
					space and show how a longer snippet of text affects the surrounding content. We'll repeat it
					often
					to keep the demonstration flowing, so be on the lookout for this exact same string of text.</p>
				<h3>Example table</h3>
				<p>And don't forget about tables in these posts:</p>
				<table class="table">
					<thead>
						<tr>
							<th>Name</th>
							<th>Upvotes</th>
							<th>Downvotes</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td>Alice</td>
							<td>10</td>
							<td>11</td>
						</tr>
						<tr>
							<td>Bob</td>
							<td>4</td>
							<td>3</td>
						</tr>
						<tr>
							<td>Charlie</td>
							<td>7</td>
							<td>9</td>
						</tr>
					</tbody>
					<tfoot>
						<tr>
							<td>Totals</td>
							<td>21</td>
							<td>23</td>
						</tr>
					</tfoot>
				</table>

				<p>This is some additional paragraph placeholder content. It's a slightly shorter version of the
					other
					highly repetitive body text used throughout.</p>
			</article>

			<article class="blog-post">
				<h2 class="blog-post-title mb-1">New feature</h2>
				<p class="blog-post-meta">December 14, 2020 by <a href="#">Chris</a></p>

				<p>This is some additional paragraph placeholder content. It has been written to fill the available
					space and show how a longer snippet of text affects the surrounding content. We'll repeat it
					often
					to keep the demonstration flowing, so be on the lookout for this exact same string of text.</p>
				<ul>
					<li>First list item</li>
					<li>Second list item with a longer description</li>
					<li>Third list item to close it out</li>
				</ul>
				<p>This is some additional paragraph placeholder content. It's a slightly shorter version of the
					other
					highly repetitive body text used throughout.</p>
			</article>

			<nav class="blog-pagination" aria-label="Pagination">
				<a class="btn btn-outline-primary rounded-pill" href="#">Older</a>
				<a class="btn btn-outline-secondary rounded-pill disabled">Newer</a>
			</nav>

		</div>

		<div class="col-md-4">
			<div class="p-4 mb-3 bg-body-tertiary rounded">
				<h4 class="fst-italic">About</h4>
				<p class="mb-0">Customize this section to tell your visitors a little bit about your
					publication,
					writers, content, or something else entirely. Totally up to you.</p>
			</div>

			<div class="p-4">
				<h4 class="fst-italic">Archives</h4>
				<ol class="list-unstyled mb-0">
					<li><a href="#">March 2021</a></li>
					<li><a href="#">February 2021</a></li>
					<li><a href="#">January 2021</a></li>
					<li><a href="#">December 2020</a></li>
					<li><a href="#">November 2020</a></li>
					<li><a href="#">October 2020</a></li>
					<li><a href="#">September 2020</a></li>
					<li><a href="#">August 2020</a></li>
					<li><a href="#">July 2020</a></li>
					<li><a href="#">June 2020</a></li>
					<li><a href="#">May 2020</a></li>
					<li><a href="#">April 2020</a></li>
				</ol>
			</div>

			<div class="p-4">
				<h4 class="fst-italic">Elsewhere</h4>
				<ol class="list-unstyled">
					<li><a href="#">GitHub</a></li>
					<li><a href="#">Twitter</a></li>
					<li><a href="#">Facebook</a></li>
				</ol>
			</div>
		</div>
	</div>
</section>
{% endblock %}

templates/events/events.html
{% extends "base.html" %}

{% block content %}
<section class="container pt-5">
	<div class="row">
		<div class="col-12 text-center">
			<h1 class="text-body-emphasis">The events</h1>
			<p class="col-lg-8 mx-auto lead">
				This takes the basic jumbotron above and makes its background
				edge-to-edge with a <code>.container</code> inside to align content.
				Similar to above, it's been recreated with built-in grid and utility
				classes.
			</p>
		</div>
		<div class="col-12 text-center">
			<img src="/assets/img/star.png" alt="star">
			<img src="/assets/img/star.png" alt="star">
			<img src="/assets/img/star.png" alt="star">
			<img src="/assets/img/star.png" alt="star">
			<img src="/assets/img/star.png" alt="star">
		</div>
	</div>
</section>
<section class="album py-5">
	<div class="container">
		<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
			<div class="col">
				<div class="card shadow-sm">
					<div class="card-header">Featured</div>
					<div class="card-body">
						<p class="card-text">This is a wider card with supporting text below as a natural
							lead-in to
							additional content. This content is a little bit longer.</p>
						<div class="d-flex justify-content-between align-items-center">
							<div class="btn-group">
								<button type="button" class="btn btn-sm btn-outline-secondary">View</button>
								<button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
							</div>
							<small class="text-body-secondary">9 mins</small>
						</div>
					</div>
				</div>
			</div>
			<div class="col">
				<div class="card shadow-sm">
					<div class="card-header">Featured</div>
					<div class="card-body">
						<p class="card-text">This is a wider card with supporting text below as a natural
							lead-in to
							additional content. This content is a little bit longer.</p>
						<div class="d-flex justify-content-between align-items-center">
							<div class="btn-group">
								<button type="button" class="btn btn-sm btn-outline-secondary">View</button>
								<button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
							</div>
							<small class="text-body-secondary">9 mins</small>
						</div>
					</div>
				</div>
			</div>
			<div class="col">
				<div class="card shadow-sm">
					<div class="card-header">Featured</div>
					<div class="card-body">
						<p class="card-text">This is a wider card with supporting text below as a natural
							lead-in to
							additional content. This content is a little bit longer.</p>
						<div class="d-flex justify-content-between align-items-center">
							<div class="btn-group">
								<button type="button" class="btn btn-sm btn-outline-secondary">View</button>
								<button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
							</div>
							<small class="text-body-secondary">9 mins</small>
						</div>
					</div>
				</div>
			</div>
			<div class="col">
				<div class="card shadow-sm">
					<div class="card-header">Featured</div>
					<div class="card-body">
						<p class="card-text">This is a wider card with supporting text below as a natural
							lead-in to
							additional content. This content is a little bit longer.</p>
						<div class="d-flex justify-content-between align-items-center">
							<div class="btn-group">
								<button type="button" class="btn btn-sm btn-outline-secondary">View</button>
								<button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
							</div>
							<small class="text-body-secondary">9 mins</small>
						</div>
					</div>
				</div>
			</div>
			<div class="col">
				<div class="card shadow-sm">
					<div class="card-header">Featured</div>
					<div class="card-body">
						<p class="card-text">This is a wider card with supporting text below as a natural
							lead-in to
							additional content. This content is a little bit longer.</p>
						<div class="d-flex justify-content-between align-items-center">
							<div class="btn-group">
								<button type="button" class="btn btn-sm btn-outline-secondary">View</button>
								<button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
							</div>
							<small class="text-body-secondary">9 mins</small>
						</div>
					</div>
				</div>
			</div>
			<div class="col">
				<div class="card shadow-sm">
					<div class="card-header">Featured</div>
					<div class="card-body">
						<p class="card-text">This is a wider card with supporting text below as a natural
							lead-in to
							additional content. This content is a little bit longer.</p>
						<div class="d-flex justify-content-between align-items-center">
							<div class="btn-group">
								<button type="button" class="btn btn-sm btn-outline-secondary">View</button>
								<button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
							</div>
							<small class="text-body-secondary">9 mins</small>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

templates/friends/friends.html
{% extends "base.html" %}

{% block content %}
<section class="container pt-5">
	<div class="row">
		<div class="col-12 text-center">
			<h1 class="text-body-emphasis">The friends</h1>
			<p class="col-lg-8 mx-auto lead">
				This takes the basic jumbotron above and makes its background
				edge-to-edge with a <code>.container</code> inside to align content.
				Similar to above, it's been recreated with built-in grid and utility
				classes.
			</p>
		</div>
		<div class="col-12 text-center">
			<img src="/assets/img/star.png" alt="star">
			<img src="/assets/img/star.png" alt="star">
			<img src="/assets/img/star.png" alt="star">
			<img src="/assets/img/star.png" alt="star">
			<img src="/assets/img/star.png" alt="star">
		</div>
	</div>
</section>
<section class="album py-5">
	<div class="container">
		<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
			<div class="col">
				<div class="card shadow-sm">
					<div class="card-header">Featured</div>
					<div class="card-body">
						<p class="card-text">This is a wider card with supporting text below as a natural
							lead-in to
							additional content. This content is a little bit longer.</p>
						<div class="d-flex justify-content-between align-items-center">
							<div class="btn-group">
								<button type="button" class="btn btn-sm btn-outline-secondary">View</button>
								<button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
							</div>
							<small class="text-body-secondary">9 mins</small>
						</div>
					</div>
				</div>
			</div>
			<div class="col">
				<div class="card shadow-sm">
					<div class="card-header">Featured</div>
					<div class="card-body">
						<p class="card-text">This is a wider card with supporting text below as a natural
							lead-in to
							additional content. This content is a little bit longer.</p>
						<div class="d-flex justify-content-between align-items-center">
							<div class="btn-group">
								<button type="button" class="btn btn-sm btn-outline-secondary">View</button>
								<button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
							</div>
							<small class="text-body-secondary">9 mins</small>
						</div>
					</div>
				</div>
			</div>
			<div class="col">
				<div class="card shadow-sm">
					<div class="card-header">Featured</div>
					<div class="card-body">
						<p class="card-text">This is a wider card with supporting text below as a natural
							lead-in to
							additional content. This content is a little bit longer.</p>
						<div class="d-flex justify-content-between align-items-center">
							<div class="btn-group">
								<button type="button" class="btn btn-sm btn-outline-secondary">View</button>
								<button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
							</div>
							<small class="text-body-secondary">9 mins</small>
						</div>
					</div>
				</div>
			</div>
			<div class="col">
				<div class="card shadow-sm">
					<div class="card-header">Featured</div>
					<div class="card-body">
						<p class="card-text">This is a wider card with supporting text below as a natural
							lead-in to
							additional content. This content is a little bit longer.</p>
						<div class="d-flex justify-content-between align-items-center">
							<div class="btn-group">
								<button type="button" class="btn btn-sm btn-outline-secondary">View</button>
								<button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
							</div>
							<small class="text-body-secondary">9 mins</small>
						</div>
					</div>
				</div>
			</div>
			<div class="col">
				<div class="card shadow-sm">
					<div class="card-header">Featured</div>
					<div class="card-body">
						<p class="card-text">This is a wider card with supporting text below as a natural
							lead-in to
							additional content. This content is a little bit longer.</p>
						<div class="d-flex justify-content-between align-items-center">
							<div class="btn-group">
								<button type="button" class="btn btn-sm btn-outline-secondary">View</button>
								<button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
							</div>
							<small class="text-body-secondary">9 mins</small>
						</div>
					</div>
				</div>
			</div>
			<div class="col">
				<div class="card shadow-sm">
					<div class="card-header">Featured</div>
					<div class="card-body">
						<p class="card-text">This is a wider card with supporting text below as a natural
							lead-in to
							additional content. This content is a little bit longer.</p>
						<div class="d-flex justify-content-between align-items-center">
							<div class="btn-group">
								<button type="button" class="btn btn-sm btn-outline-secondary">View</button>
								<button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
							</div>
							<small class="text-body-secondary">9 mins</small>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}